// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.0
// source: credentialsfetcher.proto
package grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialsFetcherService_AddKerberosLease_FullMethodName                  = "/credentialsfetcher.CredentialsFetcherService/AddKerberosLease"
	CredentialsFetcherService_AddNonDomainJoinedKerberosLease_FullMethodName   = "/credentialsfetcher.CredentialsFetcherService/AddNonDomainJoinedKerberosLease"
	CredentialsFetcherService_RenewNonDomainJoinedKerberosLease_FullMethodName = "/credentialsfetcher.CredentialsFetcherService/RenewNonDomainJoinedKerberosLease"
	CredentialsFetcherService_DeleteKerberosLease_FullMethodName               = "/credentialsfetcher.CredentialsFetcherService/DeleteKerberosLease"
	CredentialsFetcherService_HealthCheck_FullMethodName                       = "/credentialsfetcher.CredentialsFetcherService/HealthCheck"
	CredentialsFetcherService_AddKerberosArnLease_FullMethodName               = "/credentialsfetcher.CredentialsFetcherService/AddKerberosArnLease"
	CredentialsFetcherService_RenewKerberosArnLease_FullMethodName             = "/credentialsfetcher.CredentialsFetcherService/RenewKerberosArnLease"
)

// CredentialsFetcherServiceClient is the client API for CredentialsFetcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialsFetcherServiceClient interface {
	AddKerberosLease(ctx context.Context, in *CreateKerberosLeaseRequest, opts ...grpc.CallOption) (*CreateKerberosLeaseResponse, error)
	AddNonDomainJoinedKerberosLease(ctx context.Context, in *CreateNonDomainJoinedKerberosLeaseRequest, opts ...grpc.CallOption) (*CreateNonDomainJoinedKerberosLeaseResponse, error)
	RenewNonDomainJoinedKerberosLease(ctx context.Context, in *RenewNonDomainJoinedKerberosLeaseRequest, opts ...grpc.CallOption) (*RenewNonDomainJoinedKerberosLeaseResponse, error)
	DeleteKerberosLease(ctx context.Context, in *DeleteKerberosLeaseRequest, opts ...grpc.CallOption) (*DeleteKerberosLeaseResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	AddKerberosArnLease(ctx context.Context, in *KerberosArnLeaseRequest, opts ...grpc.CallOption) (*CreateKerberosArnLeaseResponse, error)
	RenewKerberosArnLease(ctx context.Context, in *RenewKerberosArnLeaseRequest, opts ...grpc.CallOption) (*RenewKerberosArnLeaseResponse, error)
}

type credentialsFetcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialsFetcherServiceClient(cc grpc.ClientConnInterface) CredentialsFetcherServiceClient {
	return &credentialsFetcherServiceClient{cc}
}

func (c *credentialsFetcherServiceClient) AddKerberosLease(ctx context.Context, in *CreateKerberosLeaseRequest, opts ...grpc.CallOption) (*CreateKerberosLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKerberosLeaseResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_AddKerberosLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsFetcherServiceClient) AddNonDomainJoinedKerberosLease(ctx context.Context, in *CreateNonDomainJoinedKerberosLeaseRequest, opts ...grpc.CallOption) (*CreateNonDomainJoinedKerberosLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNonDomainJoinedKerberosLeaseResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_AddNonDomainJoinedKerberosLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsFetcherServiceClient) RenewNonDomainJoinedKerberosLease(ctx context.Context, in *RenewNonDomainJoinedKerberosLeaseRequest, opts ...grpc.CallOption) (*RenewNonDomainJoinedKerberosLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewNonDomainJoinedKerberosLeaseResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_RenewNonDomainJoinedKerberosLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsFetcherServiceClient) DeleteKerberosLease(ctx context.Context, in *DeleteKerberosLeaseRequest, opts ...grpc.CallOption) (*DeleteKerberosLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKerberosLeaseResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_DeleteKerberosLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsFetcherServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsFetcherServiceClient) AddKerberosArnLease(ctx context.Context, in *KerberosArnLeaseRequest, opts ...grpc.CallOption) (*CreateKerberosArnLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKerberosArnLeaseResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_AddKerberosArnLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsFetcherServiceClient) RenewKerberosArnLease(ctx context.Context, in *RenewKerberosArnLeaseRequest, opts ...grpc.CallOption) (*RenewKerberosArnLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewKerberosArnLeaseResponse)
	err := c.cc.Invoke(ctx, CredentialsFetcherService_RenewKerberosArnLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialsFetcherServiceServer is the server API for CredentialsFetcherService service.
// All implementations must embed UnimplementedCredentialsFetcherServiceServer
// for forward compatibility.
type CredentialsFetcherServiceServer interface {
	AddKerberosLease(context.Context, *CreateKerberosLeaseRequest) (*CreateKerberosLeaseResponse, error)
	AddNonDomainJoinedKerberosLease(context.Context, *CreateNonDomainJoinedKerberosLeaseRequest) (*CreateNonDomainJoinedKerberosLeaseResponse, error)
	RenewNonDomainJoinedKerberosLease(context.Context, *RenewNonDomainJoinedKerberosLeaseRequest) (*RenewNonDomainJoinedKerberosLeaseResponse, error)
	DeleteKerberosLease(context.Context, *DeleteKerberosLeaseRequest) (*DeleteKerberosLeaseResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	AddKerberosArnLease(context.Context, *KerberosArnLeaseRequest) (*CreateKerberosArnLeaseResponse, error)
	RenewKerberosArnLease(context.Context, *RenewKerberosArnLeaseRequest) (*RenewKerberosArnLeaseResponse, error)
	mustEmbedUnimplementedCredentialsFetcherServiceServer()
}

// UnimplementedCredentialsFetcherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialsFetcherServiceServer struct{}

func (UnimplementedCredentialsFetcherServiceServer) AddKerberosLease(context.Context, *CreateKerberosLeaseRequest) (*CreateKerberosLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKerberosLease not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) AddNonDomainJoinedKerberosLease(context.Context, *CreateNonDomainJoinedKerberosLeaseRequest) (*CreateNonDomainJoinedKerberosLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNonDomainJoinedKerberosLease not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) RenewNonDomainJoinedKerberosLease(context.Context, *RenewNonDomainJoinedKerberosLeaseRequest) (*RenewNonDomainJoinedKerberosLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewNonDomainJoinedKerberosLease not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) DeleteKerberosLease(context.Context, *DeleteKerberosLeaseRequest) (*DeleteKerberosLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKerberosLease not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) AddKerberosArnLease(context.Context, *KerberosArnLeaseRequest) (*CreateKerberosArnLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKerberosArnLease not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) RenewKerberosArnLease(context.Context, *RenewKerberosArnLeaseRequest) (*RenewKerberosArnLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewKerberosArnLease not implemented")
}
func (UnimplementedCredentialsFetcherServiceServer) mustEmbedUnimplementedCredentialsFetcherServiceServer() {
}
func (UnimplementedCredentialsFetcherServiceServer) testEmbeddedByValue() {}

// UnsafeCredentialsFetcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialsFetcherServiceServer will
// result in compilation errors.
type UnsafeCredentialsFetcherServiceServer interface {
	mustEmbedUnimplementedCredentialsFetcherServiceServer()
}

func RegisterCredentialsFetcherServiceServer(s grpc.ServiceRegistrar, srv CredentialsFetcherServiceServer) {
	// If the following call pancis, it indicates UnimplementedCredentialsFetcherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialsFetcherService_ServiceDesc, srv)
}

func _CredentialsFetcherService_AddKerberosLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKerberosLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).AddKerberosLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_AddKerberosLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).AddKerberosLease(ctx, req.(*CreateKerberosLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsFetcherService_AddNonDomainJoinedKerberosLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNonDomainJoinedKerberosLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).AddNonDomainJoinedKerberosLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_AddNonDomainJoinedKerberosLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).AddNonDomainJoinedKerberosLease(ctx, req.(*CreateNonDomainJoinedKerberosLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsFetcherService_RenewNonDomainJoinedKerberosLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewNonDomainJoinedKerberosLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).RenewNonDomainJoinedKerberosLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_RenewNonDomainJoinedKerberosLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).RenewNonDomainJoinedKerberosLease(ctx, req.(*RenewNonDomainJoinedKerberosLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsFetcherService_DeleteKerberosLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKerberosLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).DeleteKerberosLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_DeleteKerberosLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).DeleteKerberosLease(ctx, req.(*DeleteKerberosLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsFetcherService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsFetcherService_AddKerberosArnLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KerberosArnLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).AddKerberosArnLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_AddKerberosArnLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).AddKerberosArnLease(ctx, req.(*KerberosArnLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialsFetcherService_RenewKerberosArnLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewKerberosArnLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsFetcherServiceServer).RenewKerberosArnLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialsFetcherService_RenewKerberosArnLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsFetcherServiceServer).RenewKerberosArnLease(ctx, req.(*RenewKerberosArnLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialsFetcherService_ServiceDesc is the grpc.ServiceDesc for CredentialsFetcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialsFetcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "credentialsfetcher.CredentialsFetcherService",
	HandlerType: (*CredentialsFetcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddKerberosLease",
			Handler:    _CredentialsFetcherService_AddKerberosLease_Handler,
		},
		{
			MethodName: "AddNonDomainJoinedKerberosLease",
			Handler:    _CredentialsFetcherService_AddNonDomainJoinedKerberosLease_Handler,
		},
		{
			MethodName: "RenewNonDomainJoinedKerberosLease",
			Handler:    _CredentialsFetcherService_RenewNonDomainJoinedKerberosLease_Handler,
		},
		{
			MethodName: "DeleteKerberosLease",
			Handler:    _CredentialsFetcherService_DeleteKerberosLease_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CredentialsFetcherService_HealthCheck_Handler,
		},
		{
			MethodName: "AddKerberosArnLease",
			Handler:    _CredentialsFetcherService_AddKerberosArnLease_Handler,
		},
		{
			MethodName: "RenewKerberosArnLease",
			Handler:    _CredentialsFetcherService_RenewKerberosArnLease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credentialsfetcher.proto",
}
