# Credentials Fetcher Configuration File

# Run renewal for non-domain joined instances
# This must be set to true if you're running standalone non-domain joined mode
RunRenewalNonDomainJoined =

# gMSA secret name in AWS Secrets Manager
# You must provide this string if RunRenewalNonDomainJoined = true
# This is the secret that contains the credentials of the user principal
CFGmsaSecretName = ""