#docker build -f ./Dockerfile-ubuntu-24.04 -t credential-fatcher:1.2.3 --build-arg TIME_ZONE=America/New_York  ..
#docker run -v "$(pwd)../../":/host -it --rm --entrypoint /bin/bash credential-fatcher:1.2.3 -c "cp ./credentials-fetcherd /host && cp ./credentials_fetcher_utf16_private.* /host"

FROM ubuntu:24.04 AS base
ARG TIME_ZONE
RUN if [ -z "${TIME_ZONE}" ] ; then exit 1; fi

RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" TZ="${TIME_ZONE}" \
        apt install -y git clang wget curl autoconf \
        libglib2.0-dev libboost-dev libkrb5-dev libsystemd-dev libssl-dev \
        libboost-program-options-dev libboost-filesystem-dev byacc make libjsoncpp-dev

RUN cd /root && git clone https://github.com/Kitware/CMake.git -b release \
    && cd CMake && ./configure && make -j4 &&  pwd && make install

RUN cd /root && git clone https://github.com/krb5/krb5.git -b krb5-1.21.2-final \
   && cd krb5/src && autoconf && autoreconf && ./configure && make -j4 && make install

RUN cd /root && git clone --recurse-submodules -b v1.58.0 https://github.com/grpc/grpc \
    && cd grpc/ && mkdir build && cd build \
    && cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ../ \
    && make -j4 \
    && make install

#RUN apt-get install wget -y && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
#    && dpkg -i packages-microsoft-prod.deb \
#    && rm packages-microsoft-prod.deb \
#    && apt remove 'dotnet*' 'aspnetcore*' 'netstandard*' \
#    && rm /etc/apt/sources.list.d/microsoft-prod.list \
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:dotnet/backports \
    && apt-get install -y dotnet-sdk-9.0

COPY . /root/credentials-fetcher
RUN cd /root \
    && mkdir -p credentials-fetcher/build \
    && mkdir -p /usr/lib64/glib-2.0/ \
    && ln -s '/usr/lib/x86_64-linux-gnu/glib-2.0/include/' '/usr/lib64/glib-2.0/include' \
    && ln -s /usr/include/jsoncpp/json/ /usr/include/json \
    && cd credentials-fetcher && cd build \
    && cmake ../ && make -j4 && make install

WORKDIR /root/credentials-fetcher/build

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

CMD ["/bin/bash"]

