FROM ubuntu:22.04 as base

RUN DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" \
    apt-get update \
    && apt install -y git clang wget cmake curl \
        libglib2.0-dev libboost-dev libkrb5-dev libsystemd-dev libssl-dev \
        libboost-program-options-dev libboost-filesystem-dev

RUN cd /root && git clone --recurse-submodules https://github.com/grpc/grpc \
   && cd grpc/ \
    && mkdir build \
    && cd build \
    && cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_CXX_STANDARD=17 ../ \
    && make -j4 \
    && make install

RUN apt-get update \
    && apt-get install -y dotnet-sdk-6.0

RUN cd /root && git clone -b credentials-fetcher-credfile https://github.com/fordth/credentials-fetcher \
    && mkdir -p credentials-fetcher/build \
    && mkdir -p /usr/lib64/glib-2.0/ \
    && ln -s '/usr/lib/x86_64-linux-gnu/glib-2.0/include/' '/usr/lib64/glib-2.0/include' \
    && cd credentials-fetcher \ 
    && sed -i 's/sd_journal_print/\/\/sd_journal_print/g' common/daemon.h \
    && cd build \
    && cmake -DCMAKE_CXX_STANDARD=17 ../ && make -j && make install

WORKDIR /root/credentials-fetcher/build

CMD ["/bin/bash"]
