// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.0
// source: credentialsfetcher.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type KerberosArnLeaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CredspecArns    []string               `protobuf:"bytes,1,rep,name=credspec_arns,json=credspecArns,proto3" json:"credspec_arns,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,2,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,3,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Region          string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KerberosArnLeaseRequest) Reset() {
	*x = KerberosArnLeaseRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KerberosArnLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KerberosArnLeaseRequest) ProtoMessage() {}

func (x *KerberosArnLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KerberosArnLeaseRequest.ProtoReflect.Descriptor instead.
func (*KerberosArnLeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{2}
}

func (x *KerberosArnLeaseRequest) GetCredspecArns() []string {
	if x != nil {
		return x.CredspecArns
	}
	return nil
}

func (x *KerberosArnLeaseRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *KerberosArnLeaseRequest) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *KerberosArnLeaseRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *KerberosArnLeaseRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type RenewKerberosArnLeaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Region          string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenewKerberosArnLeaseRequest) Reset() {
	*x = RenewKerberosArnLeaseRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewKerberosArnLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewKerberosArnLeaseRequest) ProtoMessage() {}

func (x *RenewKerberosArnLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewKerberosArnLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewKerberosArnLeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{3}
}

func (x *RenewKerberosArnLeaseRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *RenewKerberosArnLeaseRequest) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *RenewKerberosArnLeaseRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RenewKerberosArnLeaseRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type CreateKerberosArnLeaseResponse struct {
	state                protoimpl.MessageState       `protogen:"open.v1"`
	LeaseId              string                       `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	KrbTicketResponseMap []*KerberosTicketArnResponse `protobuf:"bytes,2,rep,name=krb_ticket_response_map,json=krbTicketResponseMap,proto3" json:"krb_ticket_response_map,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateKerberosArnLeaseResponse) Reset() {
	*x = CreateKerberosArnLeaseResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKerberosArnLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKerberosArnLeaseResponse) ProtoMessage() {}

func (x *CreateKerberosArnLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKerberosArnLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKerberosArnLeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKerberosArnLeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CreateKerberosArnLeaseResponse) GetKrbTicketResponseMap() []*KerberosTicketArnResponse {
	if x != nil {
		return x.KrbTicketResponseMap
	}
	return nil
}

type RenewKerberosArnLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewKerberosArnLeaseResponse) Reset() {
	*x = RenewKerberosArnLeaseResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewKerberosArnLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewKerberosArnLeaseResponse) ProtoMessage() {}

func (x *RenewKerberosArnLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewKerberosArnLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewKerberosArnLeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{5}
}

func (x *RenewKerberosArnLeaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type KerberosTicketArnResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CredspecArns             string                 `protobuf:"bytes,1,opt,name=credspec_arns,json=credspecArns,proto3" json:"credspec_arns,omitempty"`
	CreatedKerberosFilePaths string                 `protobuf:"bytes,2,opt,name=created_kerberos_file_paths,json=createdKerberosFilePaths,proto3" json:"created_kerberos_file_paths,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *KerberosTicketArnResponse) Reset() {
	*x = KerberosTicketArnResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KerberosTicketArnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KerberosTicketArnResponse) ProtoMessage() {}

func (x *KerberosTicketArnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KerberosTicketArnResponse.ProtoReflect.Descriptor instead.
func (*KerberosTicketArnResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{6}
}

func (x *KerberosTicketArnResponse) GetCredspecArns() string {
	if x != nil {
		return x.CredspecArns
	}
	return ""
}

func (x *KerberosTicketArnResponse) GetCreatedKerberosFilePaths() string {
	if x != nil {
		return x.CreatedKerberosFilePaths
	}
	return ""
}

type CreateKerberosLeaseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CredspecContents []string               `protobuf:"bytes,1,rep,name=credspec_contents,json=credspecContents,proto3" json:"credspec_contents,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateKerberosLeaseRequest) Reset() {
	*x = CreateKerberosLeaseRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKerberosLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKerberosLeaseRequest) ProtoMessage() {}

func (x *CreateKerberosLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKerberosLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKerberosLeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{7}
}

func (x *CreateKerberosLeaseRequest) GetCredspecContents() []string {
	if x != nil {
		return x.CredspecContents
	}
	return nil
}

type CreateKerberosLeaseResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	LeaseId                  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	CreatedKerberosFilePaths []string               `protobuf:"bytes,2,rep,name=created_kerberos_file_paths,json=createdKerberosFilePaths,proto3" json:"created_kerberos_file_paths,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateKerberosLeaseResponse) Reset() {
	*x = CreateKerberosLeaseResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKerberosLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKerberosLeaseResponse) ProtoMessage() {}

func (x *CreateKerberosLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKerberosLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKerberosLeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{8}
}

func (x *CreateKerberosLeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CreateKerberosLeaseResponse) GetCreatedKerberosFilePaths() []string {
	if x != nil {
		return x.CreatedKerberosFilePaths
	}
	return nil
}

type CreateNonDomainJoinedKerberosLeaseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CredspecContents []string               `protobuf:"bytes,1,rep,name=credspec_contents,json=credspecContents,proto3" json:"credspec_contents,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password         string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Domain           string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) Reset() {
	*x = CreateNonDomainJoinedKerberosLeaseRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNonDomainJoinedKerberosLeaseRequest) ProtoMessage() {}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNonDomainJoinedKerberosLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateNonDomainJoinedKerberosLeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{9}
}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) GetCredspecContents() []string {
	if x != nil {
		return x.CredspecContents
	}
	return nil
}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateNonDomainJoinedKerberosLeaseRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateNonDomainJoinedKerberosLeaseResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	LeaseId                  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	CreatedKerberosFilePaths []string               `protobuf:"bytes,2,rep,name=created_kerberos_file_paths,json=createdKerberosFilePaths,proto3" json:"created_kerberos_file_paths,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateNonDomainJoinedKerberosLeaseResponse) Reset() {
	*x = CreateNonDomainJoinedKerberosLeaseResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNonDomainJoinedKerberosLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNonDomainJoinedKerberosLeaseResponse) ProtoMessage() {}

func (x *CreateNonDomainJoinedKerberosLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNonDomainJoinedKerberosLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateNonDomainJoinedKerberosLeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNonDomainJoinedKerberosLeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CreateNonDomainJoinedKerberosLeaseResponse) GetCreatedKerberosFilePaths() []string {
	if x != nil {
		return x.CreatedKerberosFilePaths
	}
	return nil
}

type RenewNonDomainJoinedKerberosLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewNonDomainJoinedKerberosLeaseRequest) Reset() {
	*x = RenewNonDomainJoinedKerberosLeaseRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewNonDomainJoinedKerberosLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewNonDomainJoinedKerberosLeaseRequest) ProtoMessage() {}

func (x *RenewNonDomainJoinedKerberosLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewNonDomainJoinedKerberosLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewNonDomainJoinedKerberosLeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{11}
}

func (x *RenewNonDomainJoinedKerberosLeaseRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RenewNonDomainJoinedKerberosLeaseRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RenewNonDomainJoinedKerberosLeaseRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type RenewNonDomainJoinedKerberosLeaseResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RenewedKerberosFilePaths []string               `protobuf:"bytes,1,rep,name=renewed_kerberos_file_paths,json=renewedKerberosFilePaths,proto3" json:"renewed_kerberos_file_paths,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RenewNonDomainJoinedKerberosLeaseResponse) Reset() {
	*x = RenewNonDomainJoinedKerberosLeaseResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewNonDomainJoinedKerberosLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewNonDomainJoinedKerberosLeaseResponse) ProtoMessage() {}

func (x *RenewNonDomainJoinedKerberosLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewNonDomainJoinedKerberosLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewNonDomainJoinedKerberosLeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{12}
}

func (x *RenewNonDomainJoinedKerberosLeaseResponse) GetRenewedKerberosFilePaths() []string {
	if x != nil {
		return x.RenewedKerberosFilePaths
	}
	return nil
}

type DeleteKerberosLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKerberosLeaseRequest) Reset() {
	*x = DeleteKerberosLeaseRequest{}
	mi := &file_credentialsfetcher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKerberosLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKerberosLeaseRequest) ProtoMessage() {}

func (x *DeleteKerberosLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKerberosLeaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteKerberosLeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteKerberosLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type DeleteKerberosLeaseResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	LeaseId                  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	DeletedKerberosFilePaths []string               `protobuf:"bytes,2,rep,name=deleted_kerberos_file_paths,json=deletedKerberosFilePaths,proto3" json:"deleted_kerberos_file_paths,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeleteKerberosLeaseResponse) Reset() {
	*x = DeleteKerberosLeaseResponse{}
	mi := &file_credentialsfetcher_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKerberosLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKerberosLeaseResponse) ProtoMessage() {}

func (x *DeleteKerberosLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialsfetcher_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKerberosLeaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteKerberosLeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialsfetcher_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteKerberosLeaseResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *DeleteKerberosLeaseResponse) GetDeletedKerberosFilePaths() []string {
	if x != nil {
		return x.DeletedKerberosFilePaths
	}
	return nil
}

var File_credentialsfetcher_proto protoreflect.FileDescriptor

const file_credentialsfetcher_proto_rawDesc = "" +
	"\n" +
	"\x18credentialsfetcher.proto\x12\x12credentialsfetcher\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xcb\x01\n" +
	"\x17KerberosArnLeaseRequest\x12#\n" +
	"\rcredspec_arns\x18\x01 \x03(\tR\fcredspecArns\x12\"\n" +
	"\raccess_key_id\x18\x02 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x03 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"\xab\x01\n" +
	"\x1cRenewKerberosArnLeaseRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"\xa1\x01\n" +
	"\x1eCreateKerberosArnLeaseResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12d\n" +
	"\x17krb_ticket_response_map\x18\x02 \x03(\v2-.credentialsfetcher.KerberosTicketArnResponseR\x14krbTicketResponseMap\"7\n" +
	"\x1dRenewKerberosArnLeaseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x7f\n" +
	"\x19KerberosTicketArnResponse\x12#\n" +
	"\rcredspec_arns\x18\x01 \x01(\tR\fcredspecArns\x12=\n" +
	"\x1bcreated_kerberos_file_paths\x18\x02 \x01(\tR\x18createdKerberosFilePaths\"I\n" +
	"\x1aCreateKerberosLeaseRequest\x12+\n" +
	"\x11credspec_contents\x18\x01 \x03(\tR\x10credspecContents\"w\n" +
	"\x1bCreateKerberosLeaseResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12=\n" +
	"\x1bcreated_kerberos_file_paths\x18\x02 \x03(\tR\x18createdKerberosFilePaths\"\xa8\x01\n" +
	")CreateNonDomainJoinedKerberosLeaseRequest\x12+\n" +
	"\x11credspec_contents\x18\x01 \x03(\tR\x10credspecContents\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\"\x86\x01\n" +
	"*CreateNonDomainJoinedKerberosLeaseResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12=\n" +
	"\x1bcreated_kerberos_file_paths\x18\x02 \x03(\tR\x18createdKerberosFilePaths\"z\n" +
	"(RenewNonDomainJoinedKerberosLeaseRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"j\n" +
	")RenewNonDomainJoinedKerberosLeaseResponse\x12=\n" +
	"\x1brenewed_kerberos_file_paths\x18\x01 \x03(\tR\x18renewedKerberosFilePaths\"7\n" +
	"\x1aDeleteKerberosLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"w\n" +
	"\x1bDeleteKerberosLeaseResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12=\n" +
	"\x1bdeleted_kerberos_file_paths\x18\x02 \x03(\tR\x18deletedKerberosFilePaths2\xa4\a\n" +
	"\x19CredentialsFetcherService\x12s\n" +
	"\x10AddKerberosLease\x12..credentialsfetcher.CreateKerberosLeaseRequest\x1a/.credentialsfetcher.CreateKerberosLeaseResponse\x12\xa0\x01\n" +
	"\x1fAddNonDomainJoinedKerberosLease\x12=.credentialsfetcher.CreateNonDomainJoinedKerberosLeaseRequest\x1a>.credentialsfetcher.CreateNonDomainJoinedKerberosLeaseResponse\x12\xa0\x01\n" +
	"!RenewNonDomainJoinedKerberosLease\x12<.credentialsfetcher.RenewNonDomainJoinedKerberosLeaseRequest\x1a=.credentialsfetcher.RenewNonDomainJoinedKerberosLeaseResponse\x12v\n" +
	"\x13DeleteKerberosLease\x12..credentialsfetcher.DeleteKerberosLeaseRequest\x1a/.credentialsfetcher.DeleteKerberosLeaseResponse\x12^\n" +
	"\vHealthCheck\x12&.credentialsfetcher.HealthCheckRequest\x1a'.credentialsfetcher.HealthCheckResponse\x12v\n" +
	"\x13AddKerberosArnLease\x12+.credentialsfetcher.KerberosArnLeaseRequest\x1a2.credentialsfetcher.CreateKerberosArnLeaseResponse\x12|\n" +
	"\x15RenewKerberosArnLease\x120.credentialsfetcher.RenewKerberosArnLeaseRequest\x1a1.credentialsfetcher.RenewKerberosArnLeaseResponseB3Z1golang.a2z.com/CredentialsFetcherV2/internal/grpcb\x06proto3"

var (
	file_credentialsfetcher_proto_rawDescOnce sync.Once
	file_credentialsfetcher_proto_rawDescData []byte
)

func file_credentialsfetcher_proto_rawDescGZIP() []byte {
	file_credentialsfetcher_proto_rawDescOnce.Do(func() {
		file_credentialsfetcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credentialsfetcher_proto_rawDesc), len(file_credentialsfetcher_proto_rawDesc)))
	})
	return file_credentialsfetcher_proto_rawDescData
}

var file_credentialsfetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_credentialsfetcher_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),                         // 0: credentialsfetcher.HealthCheckRequest
	(*HealthCheckResponse)(nil),                        // 1: credentialsfetcher.HealthCheckResponse
	(*KerberosArnLeaseRequest)(nil),                    // 2: credentialsfetcher.KerberosArnLeaseRequest
	(*RenewKerberosArnLeaseRequest)(nil),               // 3: credentialsfetcher.RenewKerberosArnLeaseRequest
	(*CreateKerberosArnLeaseResponse)(nil),             // 4: credentialsfetcher.CreateKerberosArnLeaseResponse
	(*RenewKerberosArnLeaseResponse)(nil),              // 5: credentialsfetcher.RenewKerberosArnLeaseResponse
	(*KerberosTicketArnResponse)(nil),                  // 6: credentialsfetcher.KerberosTicketArnResponse
	(*CreateKerberosLeaseRequest)(nil),                 // 7: credentialsfetcher.CreateKerberosLeaseRequest
	(*CreateKerberosLeaseResponse)(nil),                // 8: credentialsfetcher.CreateKerberosLeaseResponse
	(*CreateNonDomainJoinedKerberosLeaseRequest)(nil),  // 9: credentialsfetcher.CreateNonDomainJoinedKerberosLeaseRequest
	(*CreateNonDomainJoinedKerberosLeaseResponse)(nil), // 10: credentialsfetcher.CreateNonDomainJoinedKerberosLeaseResponse
	(*RenewNonDomainJoinedKerberosLeaseRequest)(nil),   // 11: credentialsfetcher.RenewNonDomainJoinedKerberosLeaseRequest
	(*RenewNonDomainJoinedKerberosLeaseResponse)(nil),  // 12: credentialsfetcher.RenewNonDomainJoinedKerberosLeaseResponse
	(*DeleteKerberosLeaseRequest)(nil),                 // 13: credentialsfetcher.DeleteKerberosLeaseRequest
	(*DeleteKerberosLeaseResponse)(nil),                // 14: credentialsfetcher.DeleteKerberosLeaseResponse
}
var file_credentialsfetcher_proto_depIdxs = []int32{
	6,  // 0: credentialsfetcher.CreateKerberosArnLeaseResponse.krb_ticket_response_map:type_name -> credentialsfetcher.KerberosTicketArnResponse
	7,  // 1: credentialsfetcher.CredentialsFetcherService.AddKerberosLease:input_type -> credentialsfetcher.CreateKerberosLeaseRequest
	9,  // 2: credentialsfetcher.CredentialsFetcherService.AddNonDomainJoinedKerberosLease:input_type -> credentialsfetcher.CreateNonDomainJoinedKerberosLeaseRequest
	11, // 3: credentialsfetcher.CredentialsFetcherService.RenewNonDomainJoinedKerberosLease:input_type -> credentialsfetcher.RenewNonDomainJoinedKerberosLeaseRequest
	13, // 4: credentialsfetcher.CredentialsFetcherService.DeleteKerberosLease:input_type -> credentialsfetcher.DeleteKerberosLeaseRequest
	0,  // 5: credentialsfetcher.CredentialsFetcherService.HealthCheck:input_type -> credentialsfetcher.HealthCheckRequest
	2,  // 6: credentialsfetcher.CredentialsFetcherService.AddKerberosArnLease:input_type -> credentialsfetcher.KerberosArnLeaseRequest
	3,  // 7: credentialsfetcher.CredentialsFetcherService.RenewKerberosArnLease:input_type -> credentialsfetcher.RenewKerberosArnLeaseRequest
	8,  // 8: credentialsfetcher.CredentialsFetcherService.AddKerberosLease:output_type -> credentialsfetcher.CreateKerberosLeaseResponse
	10, // 9: credentialsfetcher.CredentialsFetcherService.AddNonDomainJoinedKerberosLease:output_type -> credentialsfetcher.CreateNonDomainJoinedKerberosLeaseResponse
	12, // 10: credentialsfetcher.CredentialsFetcherService.RenewNonDomainJoinedKerberosLease:output_type -> credentialsfetcher.RenewNonDomainJoinedKerberosLeaseResponse
	14, // 11: credentialsfetcher.CredentialsFetcherService.DeleteKerberosLease:output_type -> credentialsfetcher.DeleteKerberosLeaseResponse
	1,  // 12: credentialsfetcher.CredentialsFetcherService.HealthCheck:output_type -> credentialsfetcher.HealthCheckResponse
	4,  // 13: credentialsfetcher.CredentialsFetcherService.AddKerberosArnLease:output_type -> credentialsfetcher.CreateKerberosArnLeaseResponse
	5,  // 14: credentialsfetcher.CredentialsFetcherService.RenewKerberosArnLease:output_type -> credentialsfetcher.RenewKerberosArnLeaseResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_credentialsfetcher_proto_init() }
func file_credentialsfetcher_proto_init() {
	if File_credentialsfetcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credentialsfetcher_proto_rawDesc), len(file_credentialsfetcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credentialsfetcher_proto_goTypes,
		DependencyIndexes: file_credentialsfetcher_proto_depIdxs,
		MessageInfos:      file_credentialsfetcher_proto_msgTypes,
	}.Build()
	File_credentialsfetcher_proto = out.File
	file_credentialsfetcher_proto_goTypes = nil
	file_credentialsfetcher_proto_depIdxs = nil
}
