# Generated by go2rpm 1.19.0
# Check assumes a lot of network setup that is not valid
%bcond check 0

# Define _unitdir if not already defined
%{!?_unitdir: %global _unitdir /usr/lib/systemd/system}

# Define _libexec if not already defined
%{!?_libexec: %global _libexec /usr/libexec}

%define SERVICE_NAME credentials-fetcher.service

# https://github.com/aws/credentials-fetcher
%global goipath         github.com/aws/credentials-fetcher
Version:                2.0.1

%gometa -L -f

Name:           credentials-fetcher
Release:        %autorelease
Summary:        Credentials Fetcher Service is used to connect to Active Directory from Linux Instances

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND ISC AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml
# missing from upstream?
Source3:	LICENSE.txt

BuildRequires:  go-vendor-tools
BuildRequires:  krb5-devel

%description
Credentials-fetcher is a Linux daemon that retrieves gMSA credentials from
Active Directory over LDAP. It creates and refreshes kerberos tickets from gMSA
credentials. Kerberos tickets can be used by containers to run apps/services
that authenticate using Active Directory.

This (v2) is the Golang refactor of the original credentials-fetcher.

%prep
%goprep -p1
tar -xf %{S:1}
cp %{SOURCE3} .
cp %{SOURCE3} cmd/credentials-fetcher/

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/credentials-fetcherd ./cmd/credentials-fetcher/main.go

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}/usr/sbin
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}/usr/sbin/

# Create additional directory structure in buildroot
mkdir -p %{buildroot}%{_unitdir}/ecs.service.d
mkdir -p %{buildroot}/var/credentials-fetcher/{krbdir,socket,logging}
mkdir -p %{buildroot}/etc/
mkdir -p %{buildroot}%{_libexec}

# Copy service file to buildroot
cp ./configuration/bin/credentials-fetcher.service %{buildroot}%{_unitdir}/
cp ./configuration/bin/ecs-require-credentials-fetcher.conf %{buildroot}%{_unitdir}/ecs.service.d/

# Copy startup-order userdata script into libexec
install -m 0755 ./scripts/credentials-fetcher-startup-order.sh %{buildroot}%{_libexec}/

# Copy config files to buildroot
cp ./configuration/conf/credentials-fetcher.conf %{buildroot}/etc/
# Place krb5.conf in /usr/sbin to avoid conflict with system krb5-libs package
# umm... not in Fedora we don't...
# cp ./configuration/conf/krb5.conf %{buildroot}/usr/sbin/krb5.conf

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%post
chmod 644 %{_unitdir}/%{SERVICE_NAME}
/usr/bin/systemctl daemon-reload
# Since `ecs.service` gets a new dependency on `credentials-fetcher.service`, it stops on the initial reload. Start it back up if enabled
/usr/bin/systemctl is-enabled --quiet ecs.service 2>/dev/null && /usr/bin/systemctl restart ecs.service || :

%postun
/usr/bin/systemctl daemon-reload
# If this is a full removal, and *NOT* an upgrade:
if [ $1 -eq 0 ]; then
    # If the user ran our systemd dependency script, there will be an out-of-package systemd drop-in for ECS agent.
    # Remove this, and also clean up the drop-in directory, but only if it is empty after removing ours.
    if [ -d "/usr/lib/systemd/system/ecs.service.d" ]; then
        rm /usr/lib/systemd/system/ecs.service.d/require-credentials-fetcher.conf
        if [ -z "$( ls -A '/usr/lib/systemd/system/ecs.service.d' )" ]; then
            rm -rf /usr/lib/systemd/system/ecs.service.d
        fi
    fi
    # Service continues running after a full removal, so stop it
    /usr/bin/systemctl stop credentials-fetcher.service
fi

%files -f %{go_vendor_license_filelist}
%doc docs README.md
/usr/sbin/credentials-fetcherd
%config(noreplace) /etc/credentials-fetcher.conf
%{_unitdir}/credentials-fetcher.service
%{_unitdir}/ecs.service.d/ecs-require-credentials-fetcher.conf
%dir /var/credentials-fetcher
%dir /var/credentials-fetcher/krbdir
%dir /var/credentials-fetcher/socket
%dir /var/credentials-fetcher/logging
%{_libexec}/credentials-fetcher-startup-order.sh

%changelog
%autochangelog
