[Unit]
BindsTo=credentials-fetcher.service
After=credentials-fetcher.service

[Service]
ExecStartPre=/bin/bash -c 'until [ -S /var/credentials-fetcher/socket/credentials_fetcher.sock ]; do sleep 1; done'
