# Brazil package configuration
[test]
exclude-packages = [
    "golang.a2z.com/CredentialsFetcherV2/internal/grpc/proto",
    "golang.a2z.com/CredentialsFetcherV2/cmd/credentials-fetcher",
    "golang.a2z.com/CredentialsFetcherV2/tests/test_client"
]
